### ISSUE TITLE
Glob does not have an implementation file

### ISSUE THREAD

**Issue by hoichi** [BuckleTypes/bs-glob#1]
When I install `bs-glob` and run bsb, it errors with `Glob does not have an implementation file`. If I rename `glob.mli` to `glob.ml`, everything’s compiles fine.

I’m on Linux, my bs-platform is 5.0.5, here’s my bs-config:

```json
{
  "name": "nkkn",
  "sources": [
    {
      "dir": "src",
      "subdirs": true
    }
  ],
  "suffix": ".bs.js",
  "reason": {
    "react-jsx": 3
  },
  "package-specs": [
    {
      "module": "commonjs",
      "in-source": true
    }
  ],
  "bs-dependencies": [
    "bs-css",
    "bs-glob",
    "@glennsl/bs-jest",
    "bs-webapi",
    "reason-react"
  ],
  "refmt": 3
}
```

**Comment by glennsl** [comment]
Ah, yes. That's a breaking change in BuckleScript that was brought up on the [Reason forums](https://reasonml.chat/t/propose-changes-to-the-build-system-removing-interface-only-modules-support/1500/8) a while ago. I didn't expect a breaking change to come in a patch release of course, but I really shouldn't be surprised anymore as it keeps happening again and again.

Oh well, it's quick fix at least. Already done. Thanks for the heads up! :)
